name: Claude Code Action
on:
  workflow_dispatch:
  push:
    branches: [ main ]

# 権限設定を追加
permissions:
  id-token: write    # OIDC token取得に必要
  contents: read     # リポジトリ内容の読み取り
  actions: write     # Actions実行
  issues: write      # Issue作成・編集
  pull-requests: write  # PR作成・編集

jobs:
  claude-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: anthropics/claude-code-action@v0.0.16
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        github-app-id: ${{ secrets.CLAUDE_APP_ID }}
        github-app-private-key: ${{ secrets.CLAUDE_APP_PRIVATE_KEY }}